export const RUNTIME_STORAGE_KEYS: {
  readonly visualSettings: 'emptyinkpot-visual-settings';
  readonly runtimeFolderSettings: 'emptyinkpot-runtime-folder-settings';
  readonly readingHistory: 'emptyinkpot-reading-history';
  readonly readerBookmarks: 'emptyinkpot-reader-bookmarks';
  readonly readerHighlights: 'emptyinkpot-reader-highlights';
  readonly readerAnnotations: 'emptyinkpot-reader-annotations';
  readonly readerSeals: 'emptyinkpot-reader-seals';
  readonly sealDefinitions: 'emptyinkpot-seal-definitions';
  readonly stickers: 'emptyinkpot-stickers';
  readonly visualCollections: 'emptyinkpot-visual-collections';
  readonly readerTheme: 'emptyinkpot-reader-theme';
  readonly homeSidebarCollapsed: 'emptyinkpot-home-sidebar-collapsed';
  readonly bookSettings: 'emptyinkpot-book-settings';
  readonly bookLocationPrefix: 'emptyinkpot-book-location';
  readonly bookProgressPrefix: 'emptyinkpot-book-progress';
  readonly bookRecent: 'emptyinkpot-book-recent';
  readonly buildVersion: 'emptyinkpot-build-version';
  readonly buildReloadPrefix: 'emptyinkpot-build-reload';
};
